In [1]:
import numpy as np

In [2]:
!pip install numpy

In [19]:
#Task 1
N = int(input())
x = np.arange(0, N)
x[::-1]


5


array([4, 3, 2, 1, 0])

In [52]:
#Task 2
n = int(input())
i = 0
sum_ = 0
matrix = np.diag(np.arange(0, n , 1)[::-1], k=0)
for element in matrix:
    sum_ += element[i]
    i += 1
print(matrix)
print(sum_)

10
[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
45


In [ ]:
#Task 3

4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [59]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
np.linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [60]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

In [53]:
from numpy import linalg

In [3]:
#Task 4
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [48]:
def cosine(a, b):
    result = []
    for user in users_stats:
        aLength = np.sqrt( (user*user).sum() )
        bLength = np.sqrt( (next_user_stats*next_user_stats).sum() )
        cosine_res = np.dot( user, next_user_stats ) / ( aLength * bLength )
        result.append(cosine_res)
    return (result)

In [55]:
i = 0
for element in cosine(user, next_user_stats):
        i += 1
        if element == max(cosine(user, next_user_stats)):
            print(f'Самый похожий пользователь с User_id {i}')
    
 

Самый похожий пользователь с User_id 8


In [54]:
cosine(user, next_user_stats)


[0.19999999999999996,
 0.8451542547285165,
 0.3999999999999999,
 0.7905694150420948,
 0.3999999999999999,
 0.0,
 0.0,
 0.9486832980505138,
 0.0,
 0.0]